# Generated by Django 5.2.7 on 2025-10-20 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MessageModel',
            new_name='Message',
        ),
    ]
